/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Attribute: typeof import('./components/attribute.vue')['default']
    Ban: typeof import('./components/ban.vue')['default']
    Choice: typeof import('./components/choice.vue')['default']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    Genie: typeof import('./components/genie.vue')['default']
    Round: typeof import('./components/Round.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Test: typeof import('./components/test.vue')['default']
  }
}
