/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Attribute: typeof import('./pages/bp/component/attribute.vue')['default']
    Ban: typeof import('./pages/bp/component/ban.vue')['default']
    Choice: typeof import('./pages/bp/component/choice.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    Genie: typeof import('./pages/bp/component/genie.vue')['default']
    GenieEazy: typeof import('./components/genieEazy.vue')['default']
    Round: typeof import('./pages/bp/component/Round.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Test: typeof import('./components/test.vue')['default']
    Title: typeof import('./components/title.vue')['default']
    UpdateTag: typeof import('./components/updateTag.vue')['default']
  }
}
